query Organization($login: String!) {
  organization(login: $login) {
    id,
    name,
    avatarUrl,
    location,
    websiteUrl,
    repositories(first: 10) {
      nodes {
        id
        name,
        description,
        updatedAt,
        primaryLanguage {
          name,
          color
        },
        isFork,
        parent {
          name,
          url,
          nameWithOwner
        },
        stargazers {
          totalCount
        },
        forkCount,
        licenseInfo {
          spdxId,
          key
        }
      }
    },
    pinnedItems(first: 6) {
      nodes {
        ... on Repository {
          id,
          name,
            description,
            primaryLanguage {
              name,
              color
            },
            stargazers {
							totalCount
            }
          }
        }
    }
  }
}