query Organization($login: String!) {
  organization(login: $login) {
    id,
    name,
    avatarUrl,
    location,
    websiteUrl,
    pinnedItems(first: 6) {
      nodes {
        ... on Repository {
          name,
            description,
            primaryLanguage {
              name,
              color
            }
          }
        }
    }
  }
}