query Pinned ($login: String!) {
  organization(login: $login) {
    databaseId
    pinnedItems(first: 6) {
      nodes {
        ... on Repository {
          id,
          name,
            description,
            primaryLanguage {
              name,
              color
            },
            stargazers {
							totalCount
            }
          }
        }
    }
  }
}