fragment DefaultData on Repository {
  id,
  name,
  description,
  stargazers {
    totalCount
  },
  primaryLanguage {
    name,
    color
  }
}

query Pinned ($login: String!) {
  organization(login: $login) {
    databaseId
    pinnedItems(first: 6) {
      nodes {
        ... on Repository {
          ...DefaultData
        }
      }
    }
  }
}

query Search ($query: String!) {
  search(first: 30, query: $query, type: REPOSITORY) {
  	nodes {
      ... on Repository {
        ...DefaultData,
        updatedAt,
        isFork,
        isArchived,
        isMirror,
        parent {
          name,
          url,
          nameWithOwner
        },
        forkCount,
        licenseInfo {
          spdxId,
          key
        }
    	}
    }
  }
}